---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - '_snippets/*'
    - vendor/bundle/**/*
    - config/environment.rb
    - workers/*
    - 'Rakefile'
  Include:
  - 'Gemfile'
  - '**/*.rb'

# ignore method call with no args in test code only
Style/MethodCallWithoutArgsParentheses:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - Rakefile

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - Rakefile
    - app/controllers/**/*.rb

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
