# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Quality-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  Quality-Check:

    env:
      BUNDLE_WITHOUT: production
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby-version: ['3.0.2']
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Check Style and Performance
      run: bundle exec rake quality:rubocop

    - name: Check Code Smell
      run: bundle exec rake quality:reek

    - name: Run Tests
      run: |
           cp config/secrets_example.yml config/secrets.yml
           mkdir app/infrastructure/database/local
           bundle exec rake db:migrate RACK_ENV=test
           bundle exec rake spec
